name:       sitebuilder
version:    1.0.0
synopsis:   A Hakyll site builder
github:     jwiegley/sitebuilder
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System
license:    BSD3

description:
  A Hakyll site builder

dependencies:
  - base         >= 4.6
  - aeson
  - binary
  - containers
  - directory    >= 1.2
  - exceptions
  - filepath     >= 1.3
  - hakyll       >= 4.15.1.2
  - hakyll-images
  - old-locale
  - pandoc       >= 2.11 && < 2.20 || >= 3.0 && < 3.2
  - pandoc-types
  - pretty-show
  - process
  - regex-posix
  - split
  - syb
  - text
  - time
  - yaml

executables:
  sitebuilder:
    main: Main.hs
